### ISSUE TITLE
diffusion1 broken?

### ISSUE THREAD

**Issue by dlg0** [project-asgard/DG-SparseGrid#31] opened 2020-05-27 03:13 UTC
running 

```
 asgard(diffusion1,'lev',3,'deg',3,'timestep_method','BE', 'dt',0.05,'num_steps',10)
```
seems to break. 

However, changing (in `diffusion1.m`)

```
pterm1 = GRAD(num_dims,g1,+1,'N','N');
pterm2 = GRAD(num_dims,g2,-1,'D','D',BCL_fList,BCR_fList);
```
to
```
pterm1 = GRAD(num_dims,g1,+1,'D','D');
pterm2 = GRAD(num_dims,g2,-1,'N','N',BCL_fList,BCR_fList);
```
seems to fix it?

@lwonnell

**Comment by lwonnell** [comment] 2020-05-27 13:19
I don't think it's broken. Kenneth had this problem as well with diffusion1 and BE, and we determined that the time step was too large for BE. If you run it with dt = 0.01 and num_steps = 50, it should work.

**Comment by lwonnell** [comment] 2020-05-27 14:51
Apparently it's dependent on the choice of flux. When I change it to central flux it works just fine.

**Comment by dlg0** [comment] 2020-05-27 16:07
@MollyRaver do you have any thoughts on this?

**Comment by lwonnell** [comment] 2020-05-27 16:10
I am wondering if the problem is related to the presence of the source term. When I take it out and put in the correct solution, it messes up the problem further.

**Comment by dlg0** [comment] 2020-05-27 16:16
Is this a manufactured test case? If so, I’m not sure what you mean by taking out the source term?

**Comment by lwonnell** [comment] 2020-05-27 16:21
No I mean you can have a correct solution without the source term. It's cos(pi*x) exp(-pi^2*t). But when I put in that solution and take out the source term, it gives me a weird curve that isn't correct.

**Comment by dlg0** [comment] 2020-05-27 16:39
I have just added a new pde to the `reference` branch called `projecti_diff1` which is a 1D diffusion problem with an analytic solution with no source terms. It seems to work fine. So this still points to a problem with `diffusion1`

**Comment by MollyRaver** [comment] 2020-05-27 17:11
Yes. For flux as "central flux", that means value 0. We can observe the odd-even convergence rate if we ignore the error with respect to t. It means: if Deg = 2 (actually linear P1 element), it converges at the order O(h); if Deg = 3 (actually P2 element), it converges at the order O(h^4); if Deg = 4 (actually P3 element), it converges at the order O(h^3). 

The errors from flux choice, related to boundary terms, sometimes give the oscillation at the boundary. The central flux can fix it.

**Comment by lwonnell** [comment] 2020-05-27 17:30
Is the flux problem related to the size of the diffusion coefficient? I noticed that David's pde did not have the problem in diffusion1, but the diffusion coefficient is much lower. That may be because the diffusion occurs rapidly in diffusion1 and thus requires a central flux to capture? When I change diffusion1 to have nu = 0.01, it works perfectly even with the current flux terms.

**Comment by MollyRaver** [comment] 2020-05-27 18:40
The bigger coefficient may make the issue worse. If we assume -1 (left flux) and that means the boundary condition is purely from left. In this case, the right end is free. However, it should be fixed as the Dirichlet bc. There will be some un-fitted issues.

**Comment by dlg0** [comment] 2020-05-28 01:13
@MollyRaver perhaps this is a good candidate to try the global lax-freidrichs method for?

**Closed as completed** 2020-06-01 18:58 UTC
